version: 0.2
        
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install -r backend/requirements-dev.txt
      - pip install -r backend/requirements.txt
    
  build:
    commands:
      - ruff check backend/*.py --fix
      - ruff format backend/*.py
      - mypy --config-file backend/pyproject.toml backend/
