version: 0.2
        
phases:  
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 849354442967.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - cd backend/
      - VERSION=`cat VERSION`
      - docker build -t 849354442967.dkr.ecr.us-east-2.amazonaws.com/weather-backend:"$VERSION"-dev . -f Dockerfile-aws

  post_build:
    commands:
      - docker tag 849354442967.dkr.ecr.us-east-2.amazonaws.com/weather/weather-backend:"$VERSION"-dev 849354442967.dkr.ecr.us-east-2.amazonaws.com/weather/weather-backend:latest-dev
      - docker push 849354442967.dkr.ecr.us-east-2.amazonaws.com/weather/weather-backend:"$VERSION"-dev
      - docker push 849354442967.dkr.ecr.us-east-2.amazonaws.com/weather/weather-backend:latest-dev
