---
kind: pipeline
type: docker
name: weather-app

steps:
- name: backend static checks
  image: python:3.11
  commands:
    - pip install -r backend/requirements-dev.txt
    - pip install -r backend/requirements.txt
    - ruff check backend/*.py --fix
    - ruff format backend/*.py
    - mypy --config-file backend/pyproject.toml backend/

- name: backend unit-tests
  image: python:3.11
  commands:
    - pip install -r backend/requirements.txt
    - pip install -r backend/tests/requirements.txt
    - pytest backend/tests

- name: frontend tests
  image: python:3.11
  commands:
    - echo "hey"

# - name: Build backend image
#   image: plugins/docker
#   settings:
#     regsitry: gitea.jrzylab.xyz
#     username:
#       from_secret: registry_username
#     password:
#       from_secret: registry_password
#     repo: ramon/weather-app
#     context: backend/
#     # cache_from:
#     tags:
#     - '0.1.0'
#     - latest

trigger:
  branch:
    - master
    - development
  event:
    - push
    - custom