---
kind: pipeline
type: docker
name: weather-app

steps:
- name: backend static checks
  image: python:3.11
  commands:
    - pip install -r backend/requirements-dev.txt
    - pip install -r backend/requirements.txt
    - ruff check backend/*.py --fix
    - ruff format backend/*.py
    - mypy --config-file backend/pyproject.toml backend/

- name: backend unit-tests
  image: python:3.11
  commands:
    - pip install -r backend/requirements.txt
    - pip install -r backend/tests/requirements.txt
    - pytest backend/tests

- name: frontend tests
  image: python:3.11
  commands:
    - echo "hey"

trigger:
  branch:
    - master
    - development
  event:
    - push