---
kind: pipeline
type: docker
name: weather-app

steps:
- name: backend-static-checks
  image: python:3.11
  commands:
    - pip install -r backend/requirements-dev.txt
    - pip install -r backend/requirements.txt
    - ruff check backend/*.py --fix
    - ruff format backend/*.py
    - mypy --config-file backend/pyproject.toml backend/

- name: frontend-static-checks
  image: node
  commands:
    - echo "npm run lint"
    - echo "code is perfect, no analysis needed"

- name: backend-unit-tests
  image: python:3.11
  commands:
    - pip install -r backend/requirements.txt
    - pip install -r backend/tests/requirements.txt
    - pytest backend/tests
  depends_on:
    - backend-static-checks

- name: frontend-unit-tests
  image: python:3.11
  commands:
    - echo "100% sure this code works 100% of the time, every time. No test needed"
  depends_on:
    - frontend-static-checks

- name: Build backend image
  image: docker:dind
  volumes:
    - name: dockersock
      path: /var/run
  environment:
    GITEA_USERNAME:
      from_secret: GITEA_USERNAME
    GITEA_PASSWORD:
      from_secret: GITEA_PASSWORD
  commands:
    - docker login -u "${GITEA_USERNAME}" -p "${GITEA_PASSWORD}" gitea.jrzylab.xyz
    - cd backend/
    - docker build -t gitea.jrzylab.xyz/ramon/weather-app/weather-backend:"${VERSION}"-dev .
    - docker tag gitea.jrzylab.xyz/ramon/weather-app/weather-backend:"${VERSION}"-dev gitea.jrzylab.xyz/ramon/weather-app/weather-backend:latest
    - docker push gitea.jrzylab.xyz/ramon/weather-app/weather-backend:"${VERSION}"-dev
    - docker push gitea.jrzylab.xyz/ramon/weather-app/weather-backend:latest
  depends_on:
    - backend-unit-tests

- name: Build frontend image
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    GITEA_USERNAME:
      from_secret: GITEA_USERNAME
    GITEA_PASSWORD:
      from_secret: GITEA_PASSWORD
  commands:
    - env
    - echo "username - ${GITEA_USERNAME}"
    - echo "password - ${GITEA_PASSWORD}"
    - docker login -u "${GITEA_USERNAME}" -p "${GITEA_PASSWORD}" gitea.jrzylab.xyz
    - cd frontend/
    - docker build -t gitea.jrzylab.xyz/ramon/weather-app/weather-frontend:"${VERSION}"-dev .
    - docker tag gitea.jrzylab.xyz/ramon/weather-app/weather-backend:"${VERSION}"-dev gitea.jrzylab.xyz/ramon/weather-app/weather-backend:latest
    - docker push gitea.jrzylab.xyz/ramon/weather-app/weather-backend:"${VERSION}"-dev 
    - docker push gitea.jrzylab.xyz/ramon/weather-app/weather-backend:latest
  depends_on:
    - frontend-unit-tests

volumes:
- name: dockersock
  temp: {}

trigger:
  branch:
    - master
    - development
  event:
    - push
    - custom