apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

labels:
  - pairs:
      env: dev
    includeSelectors: true

namespace: dev

images:
  - name: gitea.jrzylab.xyz/ramon/weather-app/weather-backend
    newTag: latest-dev
  - name: gitea.jrzylab.xyz/ramon/weather-app/weather-frontend
    newTag: latest-dev

resources:
  - ../../base

patches:
  - path: backend-deployment.yaml
  - path: frontend-deployment.yaml
  - path: ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: weather
    path: ingress-patch.yaml
