---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: victoria-logs-nfs-pv
  namespace: logging
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Gi
  mountOptions:
    - hard
    - intr
    - nfsvers=4.1
    - rsize=32768
    - wsize=32768
  nfs:
    server: nfs.jrzylab.xyz
    path: /data/app_data/weather-app/logging/victoria-logs/
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  volumeMode: Filesystem

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: victoria-logs-nfs-pvc
#   namespace: logging
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 30Gi
#   storageClassName: nfs-storage
#   volumeName: victoria-logs-nfs-pv
#   volumeMode: Filesystem
