---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: registry-login
spec:
  encryptedData:
    .dockerconfigjson: AgB6smCvwQ7wWPW698J/IVYbU1rIgTzL7dhvdoaAjOmE38twf8f6nTyK2BDZI1FMASsZ1rSwpFUCDGNgZu/ri+8suQfCg3CZjBhBI5PHNTm/J3PEE+jHOUKR+VJtaurBhev06kpDCyrjvY7Rkb0O16Bfnm0rdzz5QpKsBWsrvQZ/6jYfbIOqQxQRHyr2W13exN9iHX26LeolrgAPvibEVvdWhNEIAUvSUwDDO2dgOhg6d+C5GpBxYum9fN/d0l1dn8sEsuX78fe+zPIgX25mkoQjcRkBiG50jnWRfFTtd/yVLvX58hADcbLZ+7bbtCI3NZjoac8N4LxFlxTlUOft+SRd73uEe0bZO+d+GJEEt/niwggV7wIronHh1fosq4JSrqEejIl7nBeEEAswJ5waSkwAycwArERAROO4CXUG3Z3mVcCQpdglk/qWa1lNz9En7JScuf2zKCek36pRMiPhuZHiko2bE2ZzLdmytsMVRlN2K9IAX2gKNj5DH5yaWRG3EzvFo0f/E3xM7KErS6sddeVIb6hJpWsNWGeyPNzrYrY4RLC6gqcfHghpevY5agGQ+DMoBIDfIX1Adno8BTnY2KakMcntZk8e95Xa8RnuQdGeqHcpIpkYuIVP1/IcXYBdLE33HG+WwKjMrRA4qHSlyGgcGye6dkXe/2djvRc/6lm3K2xS6a+7wUSZ+z6Qmakkw2Lo/fCl1mEG+ZgsZXOunOau+dLKZrirnbiqQGyW2VQ7XRkKHxAInRqZXW1BbB5QLk1fvRPqPqtN24+fDumnBShyTyoS1LHCLbYPAMNpczEVLFg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: registry-login
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: backend-api-token
spec:
  encryptedData:
    token: AgBka3e++nS2zrlMsmYYmsFs7FUJV2FT/9FexRNeuZPZRAY9mqA0gLl7dzjPdvnyebXMG4baJEdvceNtvTeAtB6mkA2RF29cZ/KtKYwd0OyZsZLHj7tEVa/Fl/Mx9XNwF4WOhwr3TJTSfddXEqpKew2ZCyX3G47MIB0vTH7I96FZ2CvWc2+FPFfBGDpme/bJH/VYHnLrrf/syQWsUtvfbvoH8Nb2bijTjOzxa/znhTs5TfPNUDyr6nEiocc97A8UNCYiEufFVMLL8Rrv1VAyQ7B/x7D/ICevdygv24+0d194F0G8DJNemXX9CEYFjGcyfkT6sIPDC75PuVmoKDEe+6npCT2C2QDr0krEyl9YOIalL1746t9PtAeYq6cO+DM8WYWHia5iFzsZ2drfy2w3uuFijHDdNcNSYlUuFEIzHkefQgmybz4w4V2OArDh/7sMAKC0qVPVrkUBSjq2vcUDyqyF/+m0letDw8EHnXSP+6XNb9V24nUquAUzjgHqFvXv3EII7tTspkJb9paNY5HahfEa8gO+s3QoLWOg7aCBnMjNXLMKrSTQRKv0F1JgFOHt2JO21zDGhR0O2wnjSqwsheWMN48xloJefrSR/TzQtaJvcWJkpQS5iRIkvnapfl3i2ZlFMwJmZvnSoLY00Bx0gzaEnHgxsv91IBlj8EoLb8/ErVwYYDF54OELl2rIPXEjdkZRhnqYZW7BxMK5qdK2GBK1h6FNxz7c0w0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: backend-api-token
    type: Opaque
