# This is for ref before sealing
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-login
data:
  .dockerconfigjson:
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-api-token
type: Opaque
data:
  token:
