---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-state-metrics
  namespace: metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  namespaceSelector:
    matchNames: 
      - metrics
  endpoints:
    - port: http

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: api-server-metrics
  namespace: metrics
spec:
  selector:
    matchLabels:
      component: apiserver
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: https
      scheme: https
      tlsConfig:
        caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      relabelConfigs:
        - sourceLabels: [__address__]
          targetLabel: __address__
          replacement: kubernetes.default.svc:443