apiVersion: operator.victoriametrics.com/v1beta1

kind: VMAgent

metadata:
  labels:
    env: prod
  name: scraper
  namespace: metrics

spec:
  selectAllByDefault: true
  remoteWrite:
    - url: "http://vmsingle-datastore.metrics.svc:8428/api/v1/write"
